#define MAX_DATE_STRING_LENGTH 24
#define DATE_SEGMENT_LENGTH 2
#define YEAR_SEGMENT_LENGTH 4 
#define FULL_DATE_LENGTH DATE_SEGMENT_LENGTH+DATE_SEGMENT_LENGTH+YEAR_SEGMENT_LENGTH
#define MAX_DATE_SEGMENTS 3
#define TIME_SEGMENT_LENGTH 2
#define TIME_ZONE_LENGTH 4
#define FULL_TIME_LENGTH TIME_SEGMENT_LENGTH*3

char validateISOTime(uint8_t *data, size_t size);
